from fastapi import FastAPI
from fastapi.responses import FileResponse
from pydantic import BaseModel

import sqlite3
import requests
import os

from dotenv import load_dotenv
from datetime import datetime
from pathlib import Path

from risk_engine import calculate_risk


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

BREVO_API_KEY = os.getenv("BREVO_API_KEY")
BREVO_SENDER_EMAIL = os.getenv("BREVO_SENDER_EMAIL")
ALERT_EMAIL = os.getenv("ALERT_EMAIL")


# ============================================================
# FASTAPI APP
# ============================================================

app = FastAPI(title="SmartGuard API")


# ============================================================
# DATABASE
# ============================================================

DATABASE = "smartguard.db"


# ============================================================
# SMARTGUARD STATE
# ============================================================

active_events = []

vibration_count = 0

unknown_rfid_count = 0


# ============================================================
# FRONTEND
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

FRONTEND_FILE = BASE_DIR / "frontend" / "dashboard.html"


# ============================================================
# CREATE DATABASE
# ============================================================

def create_database():

    connection = sqlite3.connect(DATABASE)

    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS incidents (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            event TEXT NOT NULL,
            risk_score INTEGER NOT NULL,
            risk_level TEXT NOT NULL,
            timestamp TEXT NOT NULL
        )
    """)

    connection.commit()

    connection.close()


create_database()


# ============================================================
# EMAIL ALERT FUNCTION - BREVO
# ============================================================

def send_email_alert(event, result):

    """
    Sends an automatic SmartGuard security alert
    through Brevo when the risk becomes SUSPICIOUS
    or HIGH RISK.
    """

    # --------------------------------------------------------
    # Only send email for suspicious or high-risk events
    # --------------------------------------------------------

    if result["risk_level"] == "NORMAL":
      return


    # --------------------------------------------------------
    # Check Brevo configuration
    # --------------------------------------------------------

    if not BREVO_API_KEY:
        print("EMAIL ERROR: BREVO_API_KEY is missing.")
        return

    if not BREVO_SENDER_EMAIL:
        print("EMAIL ERROR: BREVO_SENDER_EMAIL is missing.")
        return

    if not ALERT_EMAIL:
        print("EMAIL ERROR: ALERT_EMAIL is missing.")
        return


    # --------------------------------------------------------
    # Current time
    # --------------------------------------------------------

    current_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )


    # --------------------------------------------------------
    # Risk information
    # --------------------------------------------------------

    risk_score = result["risk_score"]

    risk_level = result["risk_level"]

    reasons = result.get("reasons", [])


    reasons_html = ""

    for reason in reasons:

        reasons_html += f"""
        <li>{reason}</li>
        """


    # --------------------------------------------------------
    # Email subject
    # --------------------------------------------------------

    subject = f"SmartGuard Alert - {risk_level}"


    # --------------------------------------------------------
    # Email body
    # --------------------------------------------------------

    html_content = f"""
    <html>

    <body style="font-family: Arial, sans-serif;">

        <h2>SmartGuard Security Alert</h2>

        <p>
            A security event has been detected by the
            SmartGuard system.
        </p>

        <hr>

        <h3>Security Details</h3>

        <p>
            <b>Event:</b> {event}
        </p>

        <p>
            <b>Risk Score:</b> {risk_score}/100
        </p>

        <p>
            <b>Risk Level:</b> {risk_level}
        </p>

        <p>
            <b>Time:</b> {current_time}
        </p>

        <h3>Reasons</h3>

        <ul>
            {reasons_html}
        </ul>

        <hr>

        <p>
            This alert was automatically generated by
            the SmartGuard Cyber-Physical Security System.
        </p>

    </body>

    </html>
    """


    # --------------------------------------------------------
    # Brevo API request
    # --------------------------------------------------------

    url = "https://api.brevo.com/v3/smtp/email"


    headers = {
        "accept": "application/json",
        "api-key": BREVO_API_KEY,
        "content-type": "application/json"
    }


    payload = {

        "sender": {
            "name": "SmartGuard",
            "email": BREVO_SENDER_EMAIL
        },

        "to": [
            {
                "email": ALERT_EMAIL
            }
        ],

        "subject": subject,

        "htmlContent": html_content
    }


    # --------------------------------------------------------
    # Send email
    # --------------------------------------------------------

    try:

        response = requests.post(
            url,
            headers=headers,
            json=payload,
            timeout=10
        )


        if response.status_code in [200, 201]:

            print(
                f"EMAIL SENT: {risk_level} alert sent successfully."
            )

        else:

            print(
                "EMAIL ERROR:",
                response.status_code,
                response.text
            )


    except requests.exceptions.RequestException as error:

        print(
            "EMAIL CONNECTION ERROR:",
            error
        )


# ============================================================
# SECURITY EVENT MODEL
# ============================================================

class SecurityEvent(BaseModel):

    event: str

    all_events: list[str]


# ============================================================
# HOME
# ============================================================

@app.get("/")
def home():

    return {
        "message": "SmartGuard backend is running!",
        "status": "online"
    }


# ============================================================
# DASHBOARD
# ============================================================

@app.get("/dashboard")
@app.get("/dashboard/")
def dashboard():

    return FileResponse(FRONTEND_FILE)


# ============================================================
# RISK CHECK
# ============================================================

@app.post("/risk")
def check_risk(event: SecurityEvent):

    result = calculate_risk(event.all_events)


    current_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )


    # --------------------------------------------------------
    # Save incident
    # --------------------------------------------------------

    connection = sqlite3.connect(DATABASE)

    cursor = connection.cursor()

    cursor.execute("""
        INSERT INTO incidents
        (event, risk_score, risk_level, timestamp)
        VALUES (?, ?, ?, ?)
    """, (
        event.event,
        result["risk_score"],
        result["risk_level"],
        current_time
    ))

    connection.commit()

    connection.close()


    # --------------------------------------------------------
    # Send email if suspicious/high risk
    # --------------------------------------------------------

    send_email_alert(
        event.event,
        result
    )


    return {

        "status": "success",

        "security_analysis": result

    }


# ============================================================
# RFID AUTHENTICATION
# ============================================================

@app.post("/rfid")
def rfid_authentication(card_id: str):

    global active_events

    global vibration_count

    global unknown_rfid_count


    current_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )


    # ========================================================
    # AUTHORIZED RFID
    # ========================================================

    if card_id == "authorized_rfid":

        active_events = []


        return {

            "status": "success",

            "authorized": True,

            "message": "RFID Authorized",

            "user": "Authorized User",

            "card_id": card_id,

            "timestamp": current_time

        }


    # ========================================================
    # UNKNOWN RFID
    # ========================================================

    if card_id == "unknown_rfid":

        unknown_rfid_count += 1


        if card_id not in active_events:

            active_events.append(card_id)


        # ----------------------------------------------------
        # 4 OR MORE UNAUTHORIZED ATTEMPTS
        # ----------------------------------------------------

        if unknown_rfid_count >= 4:

            result = {

                "risk_score": 100,

                "risk_level": "HIGH RISK",

                "reasons": [

                    f"Repeated unauthorized RFID attempts "
                    f"({unknown_rfid_count} times)"

                ]

            }


            message = (
                "HIGH RISK: Repeated unauthorized "
                "access attempts detected!"
            )


        # ----------------------------------------------------
        # 2 OR 3 UNAUTHORIZED ATTEMPTS
        # ----------------------------------------------------

        elif unknown_rfid_count >= 2:

            result = {

                "risk_score": 50,

                "risk_level": "SUSPICIOUS",

                "reasons": [

                    f"Multiple unauthorized RFID attempts "
                    f"({unknown_rfid_count} times)"

                ]

            }


            message = (
                "SUSPICIOUS: Multiple unauthorized "
                "access attempts detected!"
            )


        # ----------------------------------------------------
        # FIRST UNAUTHORIZED ATTEMPT
        # ----------------------------------------------------

        else:

            result = {

                "risk_score": 20,

                "risk_level": "NORMAL",

                "reasons": [

                    "Unknown RFID detected"

                ]

            }


            message = "WARNING: Unknown RFID detected!"


    # ========================================================
    # HIGH VIBRATION
    # ========================================================

    elif card_id == "high_vibration":

        vibration_count += 1


        if card_id not in active_events:

            active_events.append(card_id)


        # ----------------------------------------------------
        # UNAUTHORIZED RFID + VIBRATION
        # ----------------------------------------------------

        if unknown_rfid_count >= 2:

            result = {

                "risk_score": 100,

                "risk_level": "HIGH RISK",

                "reasons": [

                    f"Unauthorized RFID attempts: "
                    f"{unknown_rfid_count}",

                    f"Vibration detected: "
                    f"{vibration_count}"

                ]

            }


            message = (
                "HIGH RISK: Unauthorized access followed "
                "by vibration detected!"
            )


        # ----------------------------------------------------
        # REPEATED VIBRATION
        # ----------------------------------------------------

        elif vibration_count > 3:

            result = {

                "risk_score": 100,

                "risk_level": "HIGH RISK",

                "reasons": [

                    f"Repeated vibration detected "
                    f"({vibration_count} times)"

                ]

            }


            message = (
                "HIGH RISK: Repeated vibration detected!"
            )


        # ----------------------------------------------------
        # NORMAL VIBRATION EVENT
        # ----------------------------------------------------

        else:

            result = calculate_risk(
                active_events
            )

            message = "Vibration event detected"


    # ========================================================
    # OTHER SECURITY EVENTS
    # ========================================================

    elif card_id in [

        "door_forced",

        "unusual_access_time",

        "sensor_disconnection"

    ]:

        if card_id not in active_events:

            active_events.append(card_id)


        result = calculate_risk(
            active_events
        )


        message = (
            f"Security event detected: {card_id}"
        )


    # ========================================================
    # UNKNOWN EVENT
    # ========================================================

    else:

        return {

            "status": "error",

            "message": "Unknown event",

            "event": card_id

        }


    # ========================================================
    # SAVE INCIDENT TO DATABASE
    # ========================================================

    connection = sqlite3.connect(DATABASE)

    cursor = connection.cursor()


    cursor.execute("""
        INSERT INTO incidents
        (event, risk_score, risk_level, timestamp)
        VALUES (?, ?, ?, ?)
    """, (

        card_id,

        result["risk_score"],

        result["risk_level"],

        current_time

    ))


    connection.commit()

    connection.close()


    # ========================================================
    # SEND EMAIL ALERT
    # ========================================================

    send_email_alert(

        card_id,

        result

    )


    # ========================================================
    # TERMINAL LOG
    # ========================================================

    print(

        f"EVENT={card_id} | "

        f"UNAUTHORIZED_COUNT="
        f"{unknown_rfid_count} | "

        f"VIBRATION_COUNT="
        f"{vibration_count} | "

        f"RISK="
        f"{result['risk_score']} | "

        f"LEVEL="
        f"{result['risk_level']}"

    )


    # ========================================================
    # RESPONSE
    # ========================================================

    return {

        "status": "success",

        "event": card_id,

        "message": message,

        "timestamp": current_time,

        "active_events": active_events,

        "security_analysis": result

    }


# ============================================================
# GET INCIDENT HISTORY
# ============================================================

@app.get("/incidents")
def get_incidents():

    connection = sqlite3.connect(DATABASE)

    cursor = connection.cursor()


    cursor.execute("""
        SELECT id,
               event,
               risk_score,
               risk_level,
               timestamp

        FROM incidents

        ORDER BY id DESC
    """)


    rows = cursor.fetchall()

    connection.close()


    incidents = []


    for row in rows:

        incidents.append({

            "id": row[0],

            "event": row[1],

            "risk_score": row[2],

            "risk_level": row[3],

            "timestamp": row[4]

        })


    return {

        "status": "success",

        "incidents": incidents

    }


# ============================================================
# DELETE HISTORY
# ============================================================

@app.delete("/delete-history")
def delete_history():

    connection = sqlite3.connect(DATABASE)

    cursor = connection.cursor()


    cursor.execute(
        "DELETE FROM incidents"
    )


    cursor.execute(
        "DELETE FROM sqlite_sequence "
        "WHERE name='incidents'"
    )


    connection.commit()

    connection.close()


    return {

        "status": "success",

        "message":
        "Incident history deleted and "
        "ID numbering reset"

    }


# ============================================================
# RESET SECURITY SYSTEM
# ============================================================

@app.post("/reset")
def reset_security_state():

    global active_events

    global vibration_count

    global unknown_rfid_count


    # --------------------------------------------------------
    # Reset SmartGuard state
    # --------------------------------------------------------

    active_events = []

    vibration_count = 0

    unknown_rfid_count = 0


    # --------------------------------------------------------
    # Clear database
    # --------------------------------------------------------

    connection = sqlite3.connect(DATABASE)

    cursor = connection.cursor()


    cursor.execute(
        "DELETE FROM incidents"
    )


    cursor.execute(
        "DELETE FROM sqlite_sequence "
        "WHERE name='incidents'"
    )


    connection.commit()

    connection.close()


    return {

        "status": "success",

        "message":
        "Security system reset successfully",

        "active_events": []

    }